steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -f
      - Dockerfile.birdvision
      - -t
      - gcr.io/birding-app-1a446/birdvision
      - .
images:
  - gcr.io/birding-app-1a446/birdvision
